version: '3.8'

services:
  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
      - /app/node_modules
    # MEMO: .envの設定値を参照できているか分からないので念の為コメントアウトだけする
    # environment:
    #   - DATABASE_URL=api/.envに設定した値
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
